#!/usr/bin/env python3
# vim:ts=4:sts=4:sw=4:expandtab

import argparse
import logging
import os

import kolejka.settings
from kolejka.observer.server import KolejkaObserverServer

def setup():
    parser = argparse.ArgumentParser()
    parser.add_argument("-s", "--socket", type=str, default=kolejka.settings.OBSERVER_SOCKET, help='listen on socket')
    parser.add_argument("-v", "--verbose", action="store_true", default=False, help='show more info')
    parser.add_argument("-d", "--debug", action="store_true", default=False, help='show debug info')
    args = parser.parse_args()
    level=logging.WARNING
    if args.verbose:
        level=logging.INFO
    if args.debug:
        level=logging.DEBUG
    logging.basicConfig(level=level)
    return args

def run(args):
    try:
        with KolejkaObserverServer(args.socket) as server:
            server.serve_forever()
    except KeyboardInterrupt:
        raise
    except:
        traceback.print_exc()
        raise

if __name__ == '__main__':
    run(setup())
