#!/usr/bin/env python3
# vim:ts=4:sts=4:sw=4:expandtab

import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "kolejka.server.settings")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
