#!/bin/bash
# vim:ts=4:sts=4:sw=4:expandtab

MYSELF="$(readlink -f "$(which "${0}")")"
OFFICE="$(dirname "${MYSELF}")"
PROJECT="$(dirname "${OFFICE}")"

COMMON="${PROJECT}/kolejka/common/__init__.py"

PYTHONPATH="${PROJECT}" exec python3 "${COMMON}" "$@"
