#!/bin/bash
# vim:ts=4:sts=4:sw=4:expandtab

MYSELF="$(readlink -f "$(which "${0}")")"
OFFICE="$(dirname "${MYSELF}")"
PROJECT="$(dirname "${OFFICE}")"

RUNNER="${PROJECT}/kolejka/observer/runner.py"

OPTS="--debug"
#OPTS="--detach"

PYTHONPATH="${PROJECT}" exec python3 "${RUNNER}" ${OPTS} "$@"
