#!/bin/bash
# vim:ts=4:sts=4:sw=4:expandtab

MYSELF="$(readlink -f "$(which "${0}")")"
OFFICE="$(dirname "${MYSELF}")"
PROJECT="$(dirname "${OFFICE}")"

SERVER="${PROJECT}/kolejka/server/__init__.py"

OPTS=""

PYTHONPATH="${PROJECT}" exec python3 "${SERVER}" ${OPTS} "$@"
