#!/bin/bash
# vim:ts=4:sts=4:sw=4:expandtab

MYSELF="$(readlink -f "$(which "${0}")")"
OFFICE="$(dirname "${MYSELF}")"
PROJECT="$(dirname "${OFFICE}")"

OBSERVER="${PROJECT}/kolejka/observer/server.py"

OPTS="--debug"

exec sudo PYTHONPATH="${PROJECT}" python3 "${OBSERVER}" ${OPTS}
