#!/bin/bash
# vim:ts=4:sts=4:sw=4:expandtab

MYSELF="$(readlink -f "$(which "${0}")")"
OFFICE="$(dirname "${MYSELF}")"
PROJECT="$(dirname "${OFFICE}")"

FOREMAN="${PROJECT}/kolejka/foreman/__init__.py"

OPTS="--debug --config-file ${OFFICE}/kolejka.conf --config dev --tags dev,user:$(whoami)"

exec sudo PYTHONPATH="${PROJECT}" python3 "${FOREMAN}" ${OPTS} "$@"
