#!/bin/bash
# vim:ts=4:sts=4:sw=4:expandtab

MYSELF="$(readlink -f "$(which "${0}")")"
OFFICE="$(dirname "${MYSELF}")"
PROJECT="$(dirname "${OFFICE}")"

WORKER="${OFFICE}/kolejka-worker"

TEMP="$(mktemp -d)"
echo "${TEMP}"
mkdir -p "${TEMP}/result"

"${WORKER}" stage2 "${PROJECT}/../TASK" "${TEMP}/result"
ls -Al "${TEMP}/result"
cat "${TEMP}/result/kolejka_result.json"

"${WORKER}" execute "${PROJECT}/../TASK" "${TEMP}/res"
ls -Al "${TEMP}/res"
cat "${TEMP}/res/kolejka_result.json"

rm -rf "${TEMP}"
