#!/bin/bash
# vim:ts=4:sts=4:sw=4:expandtab

MYSELF="$(readlink -f "$(which "${0}")")"
OFFICE="$(dirname "${MYSELF}")"
PROJECT="$(dirname "${OFFICE}")"

CLIENT="${PROJECT}/kolejka/client/__init__.py"

OPTS="--debug --config-file ${OFFICE}/kolejka.conf"

PYTHONPATH="${PROJECT}" exec python3 "${CLIENT}" ${OPTS} "$@"
