#!/usr/bin/env python3
# vim:ts=4:sts=4:sw=4:expandtab

import os
import subprocess
import sys
import tempfile

squash_path = os.path.realpath(os.path.abspath(sys.argv[1]))
vmlinuz_path = os.path.realpath(os.path.abspath(sys.argv[2]))
initrd_path = os.path.realpath(os.path.abspath(sys.argv[3]))

with tempfile.TemporaryDirectory() as temp_path:
    subprocess.check_call(['unsquashfs', '-f', '-d', temp_path, squash_path, '/boot', '/vmlinuz', '/initrd.img'])
    with open(os.path.join(temp_path, 'vmlinuz'), 'rb') as vmlinuz_src:
        with open(vmlinuz_path, 'wb') as vmlinuz_dst:
            vmlinuz_dst.write(vmlinuz_src.read())
    with open(os.path.join(temp_path, 'initrd.img'), 'rb') as initrd_src:
        with open(initrd_path, 'wb') as initrd_dst:
            initrd_dst.write(initrd_src.read())
